
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxalgkqkqxrnirzjqsqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4YWxna3FrcXhybmlyempxc3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDgyMTcsImV4cCI6MjA2MDM4NDIxN30.uni1-viSrGowXOM4b5vFADuBAmzsJgAH5de2Id1r0fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
